---
 
- name: Example
 
  hosts: all
 
  tasks:
    - name: Install aptitude
      ansible.builtin.file:
        path: /home/user/awxtopgit.txt
        owner: foo
        group: foo
        mode: '0644'


